name:                cassava-records
version:             0.1.0.0
github:              "gdevanla/cassava-records"
license:             BSD3
author:              "Guru Devanla"
maintainer:          "grdvnl@gmail.com"
copyright:           "2017 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Auto-generation of records data type using the data in the provided csv or tab separated file.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/cassava-records#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- vector
- cassava
- bytestring
- text
- foldl
- template-haskell
- attoparsec
- unordered-containers

library:
  source-dirs: src

executables:
  cassava-records-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cassava-records
    - lens

tests:
  cassava-records-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cassava-records
