name:                cassava-records
version:             0.1.0.3
github:              "gdevanla/cassava-records"
license:             BSD3
author:              "Guru Devanla"
maintainer:          "grdvnl@gmail.com"
copyright:           "2018 Guru Devanla"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Auto-generation of records data type.
category:            Text, Web, CSV

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: cassava-records library helps in auto-creating record
             data types using Template Haskell by inferring types from the columns
             of a csv or compatible input file. The record and type classes
             instances generated can be seamlessly used with cassava(the haskell csv reader library) to load the
             data into these record types without dealing with any other level of
             abstraction.

             Please see README on Github at <https://github.com/gdevanla/cassava-records#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- vector
- cassava
- bytestring
- text
- foldl
- template-haskell
- attoparsec
- unordered-containers

library:
  source-dirs: src

# executables:
#   cassava-records-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - cassava-records
#     - lens
#     - pptable

tests:
  cassava-records-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cassava-records
    - tasty
    - HUnit
    - QuickCheck
    - tasty-hunit
    - tasty-quickcheck
    - containers
    - vector
